# Generated by Django 4.0.3 on 2022-03-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_weather'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='name',
            field=models.CharField(default='menai', max_length=10),
            preserve_default=False,
        ),
    ]
