# Generated by Django 4.0.3 on 2022-03-10 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_weather_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='lat',
            field=models.CharField(default='53.2209389', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='long',
            field=models.CharField(default='-4.1777091', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weather',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
